# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

variables:
- group: 'Test1'

steps:
- task: DownloadSecureFile@1
  name: downloaded_secure_file.txt  # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: secure_file.txt
- task: Bash@3
  env:
    Secret1: $(secret1)
  inputs:
    targetType: 'filePath'
    filePath: hello.sh
    arguments: one two three

# - task: Xcode@5
#   inputs:
#     scheme: ''
#     sdk: 'iphoneos'
#     configuration: 'Release'
#     xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'drop'
#     targetPath: 'LICENSE'
