# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

variables:
- group: 'Test1'

steps:
- task: Bash@3
  env:
    Secret1: $(secret1)
  inputs:
    targetType: 'filePath'
    script:
      # Write your commands here  
      # Use the environment variables input below to pass secret variables to this script
      echo "hello, ${Secret1} , ${secret} , $Secret , $secret , $(Secret) , $(secret) , $env:Secret , $env:secret"
      if [[ "${Secret1}" == "42" ]]
      then
        echo "match!"
      else
        echo "no match"
      fi
# - task: Xcode@5
#   inputs:
#     scheme: ''
#     sdk: 'iphoneos'
#     configuration: 'Release'
#     xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'drop'
#     targetPath: 'LICENSE'
